name: CI

on:
  push:
    branches: [main]

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          role-session-name: MySessionName
          role-skip-session-tagging: true
          role-duration-seconds: 1200
      
      - name: install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y libsndfile-dev
            pip install boto3
            pip install sagemaker
            pip install numpy
            pip install torch===1.5.0
            pip install torchlibrosa
            pip install container/wheel/pann-0.1.0-py3-none-any.whl
      #- name: build and push images to ECR
      #  run: |
      #    cd container
      #    sh build_and_push.sh
      - name: download pytorch model
        run: |
          curl "https://zenodo.org/record/3987831/files/Cnn14_DecisionLevelMax_mAP%3D0.385.pth?download=1" -o cnn14max.pth
          tar -cvzf cnn14max.tar.gz cnn14max.pth
          mv cnn14max.pth code/
      - name: run test cases
        run: |
          cd code/
          python test_inference.py


    